language: node_js
node_js:
- lts/boron
- node
after_script: bash <(curl -s https://codecov.io/bash)
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: QBbTq6xw3WLvhl37/GPNyLqKeYXCQjjwd3RIHPIPIcaY2JFpfmrU+NwnrEKz0RKQoUenMV5D8L8xShwu+aVvmqDQb2fedCqFjUaIFe0gMPT9Rsr9SA3wv0GyZoUTg2QzJVKz/wDrMZee4YmLQ0arTVUlh1f52vHQG4AV1V1heQaTg2qkMDG0kx9t/SunA9cXVCdYmQhQFcbkRUlqBUfFCFpW45gefJBI15HnbdZNuelhoq9PSDSQNBOiGA5vg/8dc8f+gsjh3bAI2la1fF2+h7yaoLw6yt+UNYwFDr0eWq+4XQcxCx5/PZNl3dUb0JtC0eW/6Z26QvP2wejA9/pfEFGm4dIjHUTqn9U+CD2m9xulDr4Z0kKjNh2A9nhmKWVZcURS+b25FSaun9cibXm9Ac4IHm/zBblRGpADh5YzJzVwXnXTIY4Z4JpBEVGrbBUOnLI6Kn+lxQrwqJZ44NHtV7geDhG8oJ7vJti32tIICY2nkST1FZa4vJ21gjl0kBtj1fjAdMWr2VxNkDVXvLegUgQR6aH42UEPMeq6w47Yaj4/fXbcJPcvY9CoXfT362ieOOz6/BC4rVpQmbUPqgq4ygasuwrqsmc/nONXoZ6KWrNXKDfr1ObbrL3oVZuPU2dc2vEFLlcWCAr+K2v+7KrM05tpP8QonKdTIcjikOy8I+Q=
  file:
    - "hast-util-whitespace.js"
    - "hast-util-whitespace.min.js"
  on:
    tags: true
